title: Curso de Laravel
description: > # this means to ignore newlines until "baseurl:"
  Curso de Laravel elaborado por Nacho Iborra, profesor
  de ciclos formativos en el I.E.S. San Vicente 
  (San Vicente del Raspeig, Alicante)
baseurl: "/laravel" # the subpath of your site, e.g. /blog
url: "http://nachoiborraIES.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown